### ISSUE TITLE
Getting a MySQL Error in production environment

### ISSUE THREAD

**Issue by johnnyhawley** [bymayo/craft-commerce-widgets#16]
```
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'primalgourmetsc.orders.customerId' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /home/forge/primal-gourmet.kickstandstudio.com/vendor/yiisoft/yii2/db/Command.php:1258
Stack trace:
#0 /home/forge/primal-gourmet.kickstandstudio.com/vendor/yiisoft/yii2/db/Command.php(1258): PDOStatement->execute()
#1 /home/forge/primal-gourmet.kickstandstudio.com/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT count(*)...')
#2 /home/forge/primal-gourmet.kickstandstudio.com/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /home/forge/primal-gourmet.kickstandstudio.com/vendor/bymayo/commerce-widgets/src/widgets/TopCustomers.php(83): yii\db\Command->queryAll()
#4 /home/forge/primal-gourmet.kickstandstudio.com/vendor/bymayo/commerce-widgets/src/widgets/TopCustomers.php(136): bymayo\commercewidgets\widgets\TopCustomers->getCustomers()
#5 /home/forge/primal-gourmet.kickstandstudio.com/vendor/craftcms/cms/src/controllers/DashboardController.php(517): bymayo\commercewidgets\widgets\TopCustomers->getBodyHtml()
#6 /home/forge/primal-gourmet.kickstandstudio.com/vendor/craftcms/cms/src/controllers/DashboardController.php(98): craft\controllers\DashboardController->_getWidgetInfo(Object(bymayo\commercewidgets\widgets\TopCustomers))
#7 [internal function]: craft\controllers\DashboardController->actionIndex()
#8 /home/forge/primal-gourmet.kickstandstudio.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /home/forge/primal-gourmet.kickstandstudio.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /home/forge/primal-gourmet.kickstandstudio.com/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('index', Array)
#11 /home/forge/primal-gourmet.kickstandstudio.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('index', Array)
#12 /home/forge/primal-gourmet.kickstandstudio.com/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('dashboard/index', Array)
#13 /home/forge/primal-gourmet.kickstandstudio.com/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('dashboard/index', Array)
#14 /home/forge/primal-gourmet.kickstandstudio.com/vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#15 /home/forge/primal-gourmet.kickstandstudio.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /home/forge/primal-gourmet.kickstandstudio.com/web/index.php(42): yii\base\Application->run()
#17 {main}

Next yii\db\Exception: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'primalgourmetsc.orders.customerId' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
The SQL being executed was: SELECT count(*) as totalOrders, SUM(orders.totalPrice) as totalRevenue, `orders`.`email`, `orders`.`customerId`
FROM `commerce_orders` `orders`
WHERE `orders`.`isCompleted`=1
GROUP BY `orders`.`email`
ORDER BY `totalOrders` DESC
LIMIT 5 in /home/forge/primal-gourmet.kickstandstudio.com/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /home/forge/primal-gourmet.kickstandstudio.com/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'SELECT count(*)...')
#1 /home/forge/primal-gourmet.kickstandstudio.com/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT count(*)...')
#2 /home/forge/primal-gourmet.kickstandstudio.com/vendor/yiisoft/yii2/db/Command.php(399): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /home/forge/primal-gourmet.kickstandstudio.com/vendor/bymayo/commerce-widgets/src/widgets/TopCustomers.php(83): yii\db\Command->queryAll()
#4 /home/forge/primal-gourmet.kickstandstudio.com/vendor/bymayo/commerce-widgets/src/widgets/TopCustomers.php(136): bymayo\commercewidgets\widgets\TopCustomers->getCustomers()
#5 /home/forge/primal-gourmet.kickstandstudio.com/vendor/craftcms/cms/src/controllers/DashboardController.php(517): bymayo\commercewidgets\widgets\TopCustomers->getBodyHtml()
#6 /home/forge/primal-gourmet.kickstandstudio.com/vendor/craftcms/cms/src/controllers/DashboardController.php(98): craft\controllers\DashboardController->_getWidgetInfo(Object(bymayo\commercewidgets\widgets\TopCustomers))
#7 [internal function]: craft\controllers\DashboardController->actionIndex()
#8 /home/forge/primal-gourmet.kickstandstudio.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /home/forge/primal-gourmet.kickstandstudio.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /home/forge/primal-gourmet.kickstandstudio.com/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('index', Array)
#11 /home/forge/primal-gourmet.kickstandstudio.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('index', Array)
#12 /home/forge/primal-gourmet.kickstandstudio.com/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('dashboard/index', Array)
#13 /home/forge/primal-gourmet.kickstandstudio.com/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('dashboard/index', Array)
#14 /home/forge/primal-gourmet.kickstandstudio.com/vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#15 /home/forge/primal-gourmet.kickstandstudio.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /home/forge/primal-gourmet.kickstandstudio.com/web/index.php(42): yii\base\Application->run()
#17 {main}
Additional Information:
Array
(
    [0] => 42000
    [1] => 1055
    [2] => Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'primalgourmetsc.orders.customerId' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
)

```

Seems like there was a [similar issue here](https://github.com/nystudio107/craft-similar/issues/8#issuecomment-422138858)

**Comment by bymayo** [comment]
@johnnyhawley Thanks, I actually came across this error today after updating from MySQL 5.6 > MySQL 5.7.

I'll work on a fix for this and push a release.

**Comment by bymayo** [comment]
@johnnyhawley Can you try the latest version to see if this has fixed your MySQL 5.7 issues.
